### ISSUE TITLE
Importing without Numba

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#214]
At the moment import of the latest package just fails w/o Numba.  Can we make it fail a bit more gracefully, with a suitable error message?

**Comment by mmcky** [comment]
Added support for graceful message to https://github.com/QuantEcon/QuantEcon.py/commit/43dca4ad969e44bb753c152e8f7768febea6fb68
in PR https://github.com/QuantEcon/QuantEcon.py/pull/211

```python
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import quantecon
Traceback (most recent call last):
  File "/home/matthewmckay/repos-collab/QuantEcon.py/quantecon/__init__.py", line 6, in <module>
    import numba
ImportError: No module named 'numba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matthewmckay/repos-collab/QuantEcon.py/quantecon/__init__.py", line 8, in <module>
    raise ImportError("Cannot import numba from current anaconda distribution. Please run `conda install numba` to install the latest version.")
ImportError: Cannot import numba from current anaconda distribution. Please run `conda install numba` to install the latest version.
```

**Comment by mmcky** [comment]
@jstac closing this issue now.
