### ISSUE TITLE
make test-all not running 

### ISSUE THREAD

**Issue by timilak** [QuantEcon/QuantEcon.py#522]
I am trying to install QuantEcon on my Mac. When I run make install it runs fine but make test-all gives me a Module Not Found Error:

Running nosetests on test suite ...
nosetests -v
Failure: ModuleNotFoundError (No module named 'normal_form_game') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'normal_form_game')

**Comment by timilak** [comment]
Following up on the earlier query, below is the complete trail of the failing make command. Any help is highly appreciated. 

-- 

> make test-all
Running nosetests on test suite ...
nosetests -v
Failure: ModuleNotFoundError (No module named 'normal_form_game') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'normal_form_game')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/anaconda3/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/anaconda3/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/timilakulkarni/QuantEcon.py-master/quantecon/__init__.py", line 15, in <module>
    from . import game_theory
  File "/Users/timilakulkarni/QuantEcon.py-master/quantecon/game_theory/__init__.py", line 6, in <module>
    from normal_form_game import Player, NormalFormGame
ModuleNotFoundError: No module named 'normal_form_game'

----------------------------------------------------------------------
Ran 1 test in 6.609s

FAILED (errors=1)
make: *** [test] Error 1

**Comment by timilak** [comment]
Hi all,

I think this error has been resolved. I went to the Makefile and converted all the 'python's to 'python3'. Also, I installed tables on my Mac, which was not previously there.

**Comment by mmcky** [comment]
sorry for slow response @timilak -- glad you got it figured out. Some os x systems default to `python27` for `python` rather than `python3`. But it looks like you were using `python3` in the error message.
