### ISSUE TITLE
[Bug]: Error with period of Markov Chain with custom state_values

### ISSUE THREAD

**Issue by Smit-create** [QuantEcon/QuantEcon.py#676]
```py
>>> import quantecon as qe
>>> import numpy as np
>>> P = np.array([
...     [0.1, 0.9],
...     [0.0, 1.0]
... ])
>>> s = np.arange(1, 3)
>>> s
array([1, 2])
>>> mc = qe.MarkovChain(P, s)
```

Error:
```console
>>> mc.period
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thebigbool/opt/anaconda3/lib/python3.9/site-packages/quantecon/markov/core.py", line 365, in period
    period = self.digraph.subgraph(rec_class).period
  File "/Users/thebigbool/opt/anaconda3/lib/python3.9/site-packages/quantecon/_graph_tools.py", line 350, in subgraph
    adj_matrix = self.csgraph[np.ix_(nodes, nodes)]
  File "/Users/thebigbool/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "/Users/thebigbool/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/_index.py", line 138, in _validate_indices
    row = self._asindices(row, M)
  File "/Users/thebigbool/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/_index.py", line 170, in _asindices
    raise IndexError('index (%d) out of range' % max_indx)
IndexError: index (2) out of range
```

**Comment by Smit-create** [comment]
Found the bug:
https://github.com/QuantEcon/QuantEcon.py/blob/b1c0cdfc2e4ace7242dee8fb1c1e20a46b42693b/quantecon/markov/core.py#L360-L366

It should be `self.recurrent_classes_indices` on line 360.

**Comment by Smit-create** [comment]
I will open a PR to fix this once the high-priority PRs are merged.

**Comment by oyamad** [comment]
@Smit-create Yes, you are right. Thanks for spotting the bug!
