### ISSUE TITLE
Bug in robust_monopolist.py

### ISSUE THREAD

**Issue by jstac** [QuantEcon/QuantEcon.py#92]
Traceback (most recent call last):
  File "robust_monopolist.py", line 132, in <module>
    Po, Fo, do = optimal_lq.stationary_values()
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/lqcontrol.py", line 206, in stationary_values
    P = solve_discrete_riccati(A0, B0, R, Q, N)
  File "/home/matthewmckay/anaconda/lib/python2.7/site-packages/quantecon/matrix_eqn.py", line 195, in solve_discrete_riccati
    raise ValueError(fail_msg.format(i))
ValueError: Convergence failed after 501 iterations.

**Comment by spencerlyon2** [comment]
ping.

@cc7768 do you know anything about this?

**Comment by cc7768** [comment]
@spencerlyon2 Nope.

**Comment by jstac** [comment]
@mmcky I can't remember the issue here.  This looks like a bug that you found.  Any thoughts?

**Comment by mmcky** [comment]
Indeed. This error is a result of running the ``robust_monopolist.py`` example file contained in ``examples/``. We discovered this when running the ``tests/test_directory_pyfiles.py``.

**Comment by mmcky** [comment]
Just ran ``robust_monopolist.py`` and the figures are produced. This seems to be resolved. Closing.
